DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS ITEMS CASCADE;
DROP TABLE IF EXISTS BOOKINGS CASCADE;
DROP TABLE IF EXISTS REQUESTS CASCADE;
DROP TABLE IF EXISTS COMMENTS CASCADE;


CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    email varchar(100) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS ITEMS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(512),
    is_available boolean,
    owner_id BIGINT,
    request_id BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT,
    booker_id BIGINT,
    status varchar(20),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REQUESTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    description varchar(512),
    requestor_id BIGINT,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COMMENTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    text varchar(512),
    item_id BIGINT,
    author_id BIGINT,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE ITEMS
    ADD FOREIGN KEY (OWNER_ID) REFERENCES USERS (ID);
ALTER TABLE ITEMS
    ADD FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS (ID);
ALTER TABLE BOOKINGS
    ADD FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID);
ALTER TABLE BOOKINGS
    ADD FOREIGN KEY (BOOKER_ID) REFERENCES USERS (ID);
ALTER TABLE REQUESTS
    ADD FOREIGN KEY (REQUESTOR_ID) REFERENCES USERS (ID);
ALTER TABLE COMMENTS
    ADD FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID);
ALTER TABLE COMMENTS
    ADD FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID);